### ISSUE TITLE
Database auto-update for Basic Authentication does not work under some conditions

### ISSUE THREAD

**Issue by DanielBertocci** [FraunhoferIOSB/FROST-Server#1653] opened 2023-07-27 14:07 UTC
I write to find inspiration to investigate the following issue I am facing:
If I enable Basic Authentication of FROST Server I cannot use the default credentials (like admin,admin) because the tables are not created.

The autoupdate for the entities works, indeed I am in a situation where the databasechangelog is in this situation:
![image](https://github.com/FraunhoferIOSB/FROST-Server/assets/10078791/3269ed6a-8aa1-4694-9f54-3cbb22f13196)

Even if I try to force the Database update I have problems because I cannot authenticate as admin. I have notice the following log on the first HTTP request to a protected endpoint, and despite it claims the database is updated, no table is created and not update is in the databasechangelog. This appears even if reboot the container and try again:

```console
scripts-web-1                    | 14:02:16.681 INFO      d.f.i.i.f.auth.basic.DatabaseHandler - Running database update for de.fraunhofer.iosb.ilt.frostserver.auth.basic.BasicAuthProvider
scripts-web-1                    | 14:02:16.788 INFO                        liquibase.database - Set default schema name to public
scripts-web-1                    | 14:02:16.869 INFO                     liquibase.lockservice - Successfully acquired change log lock
scripts-web-1                    | 14:02:17.004 INFO                       liquibase.changelog - Reading from public.databasechangelog
scripts-web-1                    | Database is up to date, no changesets to execute
scripts-web-1                    | 14:02:17.122 INFO                            liquibase.util - UPDATE SUMMARY
scripts-web-1                    | 14:02:17.122 INFO                            liquibase.util - Run:                          5
scripts-web-1                    | 14:02:17.122 INFO                            liquibase.util - Previously run:               0
scripts-web-1                    | 14:02:17.123 INFO                            liquibase.util - Filtered out:                 0
scripts-web-1                    | 14:02:17.123 INFO                            liquibase.util - -------------------------------
scripts-web-1                    | 14:02:17.123 INFO                            liquibase.util - Total change sets:            5
scripts-web-1                    | 
scripts-web-1                    | 
scripts-web-1                    | UPDATE SUMMARY
scripts-web-1                    | Run:                          5
scripts-web-1                    | Previously run:               0
scripts-web-1                    | Filtered out:                 0
scripts-web-1                    | -------------------------------
scripts-web-1                    | Total change sets:            5
scripts-web-1                    | 
scripts-web-1                    | 14:02:17.124 INFO                            liquibase.util - Update summary generated
scripts-web-1                    | 14:02:17.173 INFO                     liquibase.lockservice - Successfully released change log lock
scripts-web-1                    | 14:02:17.229 INFO                     liquibase.lockservice - Successfully released change log lock
scripts-web-1                    | 14:02:17.237 INFO                         liquibase.command - Command execution complete
scripts-web-1                    | 14:02:17.246 INFO      d.f.i.i.f.auth.basic.DatabaseHandler - Database-update successful.
```

**Setup:**
- Postgres Flexible Server on Azure (version 14 or 15) just deployed, so completely empty.
- Docker of image of fraunhoferiosb/frost-server-http:latest running locally (or in a container in Azure) with the following env variables:

```- serviceRootUrl=http://localhost:8080/FROST-Server
      - persistence_autoUpdateDatabase=true
      - persistence_db_driver=org.postgresql.Driver
      - persistence_db_url=jdbc:postgresql://{{service}}.postgres.database.azure.com/{{database}}?sslmode=require
      - persistence_db_username=username
      - persistence_db_password=password
      - persistence_idGenerationMode=ServerAndClientGenerated
      - auth_provider=de.fraunhofer.iosb.ilt.frostserver.auth.basic.BasicAuthProvider
      - auth_allowAnonymousRead=false
      - auth_authenticateOnly=false
      - auth_realmName=FROST-Server
      - auth_db_driver=org.postgresql.Driver
      - auth_db_url=jdbc:postgresql://{{service}}.postgres.database.azure.com/{{database}}?sslmode=require
      - auth_db_username=username
      - auth_db_password=password
      - auth_autoUpdateDatabase=true
      - auth.plainTextPassword=false
      - persistence_countMode=ESTIMATE_LIMIT
      - plugins_coreModel_idType=LONG
      - plugins_coreModel_idType_thing=STRING
      - plugins_multiDatastream_enable=false
```

I have investigated many options and if I use docker-compose (with also Postgres in a local container) like in the [following repository](https://github.com/hylkevds/FROST-Server.Plugin.SecurityTest/) I do not have this issue. Any suggestions?

**Comment by hylkevds** [comment] 2023-07-27 18:56
I've also noticed this, very irregularly, and hard to reproduce reliable. It's very bizarre. 

Liquibase claims it updated the database successfully, and when you call the DatabaseUpdate script, it says there's nothing left to do. But when you access the database the tables are not there, and also the entries in the DatabaseChangeLog are not there.
Restarting the server causes Liquibase to re-run the updates, since obviously they did not happen.

It's like the updates happen in a transaction that only Liquibase can see that is never committed...

For now I did notice a workaround. If you _disable_ `persistence_autoUpdateDatabase` but keep `auth_autoUpdateDatabase` _enabled_ it works. The auth tables are initialised when they are needed the first time (and not on the start of FROST) and running Liquibase form the Database Update script works correctly. This also leads me to suspect the issue is in how Liquibase accesses the connection when it is triggered during service start...

By the way, it's quite brave of you to already experiment with the Fine Grained security implementation :) Would you mind telling some more about your use cases? If you can't post that here, feel free to drop me an email...

**Comment by hylkevds** [comment] 2023-07-28 10:22
It's a bug in Liquibase:
https://forum.liquibase.org/t/bug-in-v4-21-changesets-are-not-run-because-abstractupdatecommandstep-isuptodatefastcheck-incorrectly-caches-value-across-schemas/8286

https://github.com/liquibase/liquibase/issues/4304

**Comment by hylkevds** [comment] 2023-07-28 11:28
I've implemented a work-around for the Liquibase bug.

**Closed as completed** 2023-07-28 12:56 UTC
